config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  root 'genres#index'
  resources :users
  resources :genres do
    resources :programs do
      resources :programs, only: :index, defaults: { format: "json"}
      resources :likes, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :programs
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # before_action :set_genre
  # before_action :set_program
  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
    # binding.pry
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @genre = Genre.new
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  
  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
    
    # def set_program
    #   @program = Program.find(params[:id])
    # end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.haml
= form_for @genre do |f|
  - if @genre.errors.any?
    #error_explanation
      %h2= "#{pluralize(@genre.errors.count, "error")} prohibited this genre from being saved:"
      %ul
        - @genre.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/genres/edit.html.haml
%h1 Editing genre

= render 'form'

= link_to 'Show', @genre
\|
= link_to 'Back', genres_path

app/views/genres/index.html.haml
.home_view
  .home_header
    = render_breadcrumbs separator: ' > ',class: "breadcrumbs"
    .title
      = link_to "TRIPPING", root_path, id:"titling"
    .logout
      = link_to 'ログアウト', destroy_user_session_path, method: :delete
      
    .user_page
      = link_to users_path do
        = fa_icon 'user', class: 'icon'
  .main_view
    .program_search
      %input#program-search-field.chat-group-form__input{:placeholder => "探したい記事のタイトルを入力", :type => "text",size:"50×30",id:"search_btn"}
      #program-result
    .genres
      - @genres.each do |genre|
        .genre
          .genre__name
            = link_to "#{genre.name}", genre_programs_path(genre.id)

app/views/genres/new.html.haml
%h1 New genre

= render 'form'

= link_to 'Back', genres_path

app/views/genres/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @genre.name

= link_to 'Edit', edit_genre_path(@genre)
\|
= link_to 'Back', genres_path