config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  root 'genres#index'
  resources :users
  resources :genres do
    resources :programs do
      resources :programs, only: :index, defaults: { format: "json"}
      resources :likes, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  # after_validation :geocode
  mount_uploader :video
  belongs_to :genre
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  # private
  # def geocode
  #   uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=AIzaSyCgU-tSZoHVCbF7MUGiRsz79eNVfKZXRrg")
  #   res = HTTP.get(uri).to_s
  #   response = JSON.parse(res)
  #   self.latitude = response["results"][0]["geometry"]["location"]["lat"]
  #   self.longitude = response["results"][0]["geometry"]["location"]["lng"]
  # end
  is_impressionable
  
  validates :title, length: {maximum: 50} #50文字以下
  validates :text, length: {maximum: 1000} #1000文字以下
  # validates :

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  add_breadcrumb 'Home','http://localhost3000'
  before_action :set_genre
  before_action :set_program, only: [:show]
  impressionist :actions => [:show]

  def index
    add_breadcrumb 'ブログ一覧'
    @programs = @genre.programs
    respond_to do |format|
      format.html
      format.json
    end
  end

    # @program = Program.new
    # @program = Program.find(params[:id])
    # binding.pry
    # @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")

  def show
    add_breadcrumb 'ブログ一覧'
    add_breadcrumb '日記'
    add_breadcrumb @program_title, :root_path

    @programs = @genre.programs
    @program = Program.find(params[:id])
    # def like_user(user_id)
    #   likes.find_by(user_id: user_id)
    # end
    # binding.pry
    # impressionist(@program, nil, unique: [session_hash])
    # impressionist(@program, nil, unique: [session_hash])
  end

  def new
    @program = @genre.programs.new
  end

  def edit
  end

  def create
    @program = Program.create(program_params)
    # binding.pry
  end

  def search
    @program = Program.search(genre_params)
    render "index"
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
  def program_params
    params.require(:program).permit(:id,:title,:video,:text, :genre_id, :likes_conut).merge(user_id: current_user.id)
  end

  def set_genre
    @genre = Genre.find(params[:genre_id])
    Time.zone ='Tokyo'
    # binding.pry
  end

  def set_program
    @program = Program.find(params[:id])
    # binding.pry
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.haml
.forming
  = form_for @program ,:url => {:action => :create}do |f|
    - if @program.errors.any?
      #error_explanation
        %h2= "#{pluralize(@program.errors.count, "error")} prohibited this program from being saved:"
        %ul
          - @program.errors.full_messages.each do |message|
            %li= message
    .field
      %p step1 投稿ジャンルを選んでね！
      = f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--", class: 'input', id:"selection"
    .field
      %p step2 投稿タイトルを書こう！
      = f.text_field :title, class: "form-title",id:"title", placeholder:"50文字以内"
    .field
      %p step3 自由に感想を書こう！
      = f.text_area :text,id:"text", placeholder: "1000文字以内"
    .field
      %p step4 写真を載せるとgood!
      = f.file_field :video, class: "video_box", id: "file"
      %p step5 投稿ボタンを押して完了!
      = f.submit '投稿する', class: "action_btn"

app/views/programs/create.html.haml
.created
  = link_to root_path do
    %h2 投稿しました

app/views/programs/edit.html.haml
%h1 Editing program

= render 'form'

= link_to 'Show', @program
\|
= link_to 'Back', programs_path

app/views/programs/index.html.haml
.home_view
  .home_header
    .title
      = link_to "TRIPPING", root_path
    .genre_name
      %P #{@genre.name}
  .main_view
    .programs
      - @programs.each do |program|
        .program
          .program__video
            = image_tag program.video.url, class: 'image_video' if program.video.present?
          .no_image
            = "NOIMAGE" unless program.video.present?
          .program__title
            = link_to "#{program.title}","programs/#{program.id}"
          .no_title
            = link_to "NoTitle","programs/#{program.id}" unless program.title.present?
          .program__pv  
            %p PV数:   #{program.impressionist_count}

  .action
    = fa_icon 'plus', class: 'icon'
    = link_to "投稿する", new_genre_program_path 
  -# %a.btn2{:href => "#"} Home
  -# = link_to "詳細",  genre_program_path(@program.id)

app/views/programs/new.html.haml
.creating
  = link_to "TRIPPING", root_path

  = render 'form'

app/views/programs/show.html.haml
.home_view
  .home_header
    .title
      = link_to "TRIPPING", root_path
  .showing
    .top__video
      = image_tag @program.video.url, class: 'image_video' if @program.video.present?
    .no_image
      = "NOIMAGE" unless @program.video.present?
    .top_title
      %P 「#{@program.title}」
    .top_text
      %p #{@program.text}
    .top_pv
      = fa_icon 'eye', class: 'icon'
      = @program.impressionist_count
    = render 'likes/like'
-# !!!
-# %html{:lang => "ja"}
-#   %head
-#     %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
-#     %meta{:charset => "UTF-8"}/
-#     %title Sample_GoogleMap
-#     %script{:src => "http://maps.google.com/maps/api/js?key=AIzaSyCgU-tSZoHVCbF7MUGiRsz79eNVfKZXRrg&language=ja"}
-#     :css
-#       html { height: 100% }
-#       body { height: 100% }
-#       #map { height: 50%; width: 50%}
-#   %body
-#     #map
-#     :javascript
-#       var MyLatLng = new google.maps.LatLng(35.6811673, 139.7670516);
-#       var Options = {
-#        zoom: 15,      //地図の縮尺値
-#        center: MyLatLng,    //地図の中心座標
-#        mapTypeId: 'roadmap'   //地図の種類
-#       };
-#       var map = new google.maps.Map(document.getElementById('map'), Options);
  -# \|
  -# = link_to 'Back', programs_path