config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  root 'genres#index'
  resources :users
  resources :genres do
    resources :programs do
      resources :programs, only: :index, defaults: { format: "json"}
      resources :likes, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :program, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_program, only: [:destroy]
  def create
    @like = Like.create(user_id: current_user.id, program_id: params[:program_id])
    @likes = Like.where(program_id: params[:program_id])
    @programs = Program.all
    # binding.pry
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, program_id: params[:program_id])
    @like.destroy
    @likes = Like.where(program_id: params[:program_id])
    # binding.pry
  end

  def set_program
    @program = Program.find(params[:id])
    # binding.pry
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
.liking
- if @program.like_user(current_user.id)
  = button_to genre_program_like_path(program_id: @program.id),method: :delete, id: "like-destroy", remote: true do
    %span いいね解除
    = fa_icon 'heart'
    %span
      = @program.likes_count
- else
  =  button_to genre_program_likes_path(program_id: @program.id),method: :post, id: "like-create", remote: true do
    = fa_icon 'heart'
    %span
      = @program.likes_count

app/views/likes/create.js.haml
$("#like-create").html("いいね済み")

app/views/likes/destroy.js.haml
$("#like-destroy").html("#{j(render partial: 'like')");